//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int ID { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Gender { get; set; }
        public string Home_Number { get; set; }
        public string Work_Number { get; set; }
        public string Mobile_Number { get; set; }
    }
}
